### ISSUE TITLE
Doesn't compile with latest http-conduit 2.2.0

### ISSUE THREAD

**Issue by felixonmars** [yesodweb/authenticate#47]
```
[7 of 9] Compiling OpenId2.Discovery ( OpenId2/Discovery.hs, dist/build/OpenId2/Discovery.o )

OpenId2/Discovery.hs:85:11: error: Not in scope: `checkStatus'
```

Related change:

https://github.com/snoyberg/http-client/commit/b476183dd3b3a0bdb878102f9e93d785ea8d10f8

**Comment by snoyberg** [comment]
Thanks! Just waiting for Travis to confirm this fix works with older versions too, then I'll release to Hackage.
